email: "john.doe@example.com"
sources:
  - type: http
    port: 4567
  - type: udp
    port: 4568
measurementTypes:
  - name: "heartRate"
    lowerThreshold: 60
    upperThreshold: 100
sinks:
  - type: influxDB
    address: "http://localhost"
    port: 8086
  - type: udp
    address: "http://192.168.1.2"
    port: 4568