testName: HeartRate
stages:
- id: 1
  time: 10
  node:
  - id: app1
    interface:
    - id: docker0
      delay: 10ms
- id: 2
  time: 20
  node:
  - id: app1
    interface:
    - id: docker0
      delay: 0ms
- id: 3
  time: 30
  node:
  - id: app1
    interface:
    - id: docker0
      bandwidth: 100bps
- id: 4
  time: 40
  node:
  - id: app1
    interface:
    - id: docker0
      bandwidth: 200bps
- id: 5
  time: 50
  node:
  - id: app1
    interface:
    - id: docker0
      bandwidth: 1gbps
- id: 6
  time: 60
  node:
  - id: app1
    interface:
    - id: docker0
      loss: 50
- id: 7
  time: 70
  node:
  - id: app1
    interface:
    - id: docker0
      loss: 0
- id: 8
  time: 80
  node:
  - id: app1
    interface:
    - id: docker0
      status: off
- id: 9
  time: 90
  node:
  - id: app1
    interface:
    - id: docker0
      status: on